### ISSUE TITLE
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by ZENKamath** [sonyxperiadev/pygerrit#30]
Linux skm-bodi 3.8.0-19-generic #30~precise1-Ubuntu SMP Wed May 1 22:39:29 UTC 2013 i686 i686 i386 GNU/Linux

Python 2.7.3

pip install was clean had to install python-dev and python-crypto additionally
stack trace is here - http://pastebin.com/AaxmdNc6

**Comment by dpursehouse** [comment]
I'm not sure that this is a problem with pygerrit.

Seems to be a problem with paramiko:

http://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner

I just released a new version that upgrades paramiko to a later version.  Can you try with that?  If it still doesn't work, try some of the suggestions on the page mentioned above.

**Comment by dpursehouse** [comment]
Did the paramiko upgrade fix it?
