### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by eddie-dunn** [sonyxperiadev/pygerrit#34]
It would be nice to use this library for my web application that interacts with Gerrit. However, the lack of py3 support is a deal breaker.

Are there any plans to support python 3 soon?

**Comment by dpursehouse** [comment]
I haven't tried to use it with python 3, so I have no idea how mush work would be involved.

I'm not actively maintaining this project any more.  If I do any further development it will be on [pygerrit2](https://github.com/dpursehouse/pygerrit2) which is based on this but only supports REST.

**Comment by dpursehouse** [comment]
[This commit on pygerrit2](https://github.com/dpursehouse/pygerrit2/commit/c3281b416df57b6700b27abbe3f91ed1c22a0071) adds initial python 3 support for the REST part.  There may be other fixes necessary; I haven't done a great deal of testing yet.

**Comment by dpursehouse** [comment]
Closing this because I don't intend to add python 3 support here.
